### ISSUE TITLE
[Enhancement] Option to disable inventory consumption logic

### ISSUE THREAD

**Issue by dmaneyapanda** [League-of-Foundry-Developers/torch#11]
I appreciate that this mod will automatically consume torches, but in some campaigns I don't really want the players focused on details like that.  You could just Ideally there would be an option for turning the consumption tracking of torches off, and instead it just always works to turn on torchlight.

**Comment by lupestro** [comment]
Thanks for the suggestion. With this weekend's restructuring of the code, this might not be hard to do. I'll take a look.

**Comment by lupestro** [comment]
In v2.0.0 for FoundryVTT 10, published today, there is an option for "User Consumes Inventory" that will let you turn that off.

**Comment by lupestro** [comment]
Fixed in v2.x for Foundry VTT 10
