### ISSUE TITLE
[Suggestion] Option to disable check for Dancing Lights

### ISSUE THREAD

**Issue by BadIdeasBureau** [League-of-Foundry-Developers/torch#17]
The token spawn for Dancing Lights can be neat, but can also be a bunch of extra admin to move them around, when players may just want to have a light source moving with them.  As such, gating this behind a setting would be a good idea.

See, e.g. this conversation on Discord, with a user who likes the base functionality but dislikes the automatic dancing lights.
https://discord.com/channels/170995199584108546/670336046164213761/986703936448790628

**Comment by lupestro** [comment]
Torch v2.0.0 has just been released for Foundry VTT 10. It lets the user specify which light source to use, which should mitigate this problem. 

For now, only run FoundryVTT 10 on a test server. It is still *very much* a work in progress and various systems and modules may corrupt data or cause hangs that require restarts. This will improve sharply over the coming few weeks.

**Comment by lupestro** [comment]
You should be able to get everything you want by the new behavior in v2.x for Foundry VTT 10. Closing the issue.
