### ISSUE TITLE
A few missing translation strings in several languages

### ISSUE THREAD

**Issue by lupestro** [League-of-Foundry-Developers/torch#2]
Translations needed for the following:

1. "torch.dancingLightVision.name": "Give Dancing Lights Vision.",
2. "torch.dancingLightVision.hint": "When enabled, each dancing light has vision so can be used to reveal areas of the map players can't actually see."
3. "torch.gmInventoryItemName.name": "Inventory item name to use",
4. "torch.gmInventoryItemName.hint": "Name of the inventory item to use if \"GM Uses Inventory\" is set.",

- [ ] cn: (@xticme) 1, 2, 3, 4
- [ ] fr: (@Aymeeric) 1, 2
- [x] es: (@lozalojo) 1, 2
- [x] pt-br: (@rinnocenti) 1, 2
- [x] zh-tw: (@zeteticl) 1, 2, 3, 4

**Comment by zeteticl** [comment]
fixed

**Comment by rinnocenti** [comment]
`"torch.dancingLightVision.name": "Dar Visão de Luz Dançantes.",
"torch.dancingLightVision.hint": "Quando ativado, cada luz dançante que tiver visão pode ser usado para revelar areas do mapa que os jogadores não podem ver realmente."`

**Comment by lozalojo** [comment]
> * [ ]  es: (@lozalojo) 1, 2

Done!
https://github.com/RealDeuce/torch/pull/31

**Comment by lupestro** [comment]
Uh-oh - the repository moved from RealDeuce to the League-of-Foundry-Developers fork. I'll get the changes moved over!

**Comment by lozalojo** [comment]
> Uh-oh - the repository moved from RealDeuce to the League-of-Foundry-Developers fork. I'll get the changes moved over!

Oh, sorry, I didnt pay attention which repo was pulling to, sorry!

**Comment by lupestro** [comment]
No problem - your updates will be out shortly - may thanks!

**Comment by lupestro** [comment]
I am going to close this issue and open a new one for the v2.0 stream because the strings needing translation have changed.
