### ISSUE TITLE
A token with no light spells/cantrips or torches can turn on a light

### ISSUE THREAD

**Issue by leemahn** [League-of-Foundry-Developers/torch#21]
I have a level 1 human wizard that has no torches, and no light spells/cantrips.  Yet, he can turn on/off an apparently unlimited number of torches.

![image](https://user-images.githubusercontent.com/107815660/182405747-703b91fb-a17b-4a75-af5c-8b87a5f66723.png)
![image](https://user-images.githubusercontent.com/107815660/182405831-6e00099a-8fbb-40c0-b4f2-78f90bcfe54c.png)

Wondering if there's something I'm doing wrong.  All my other characters that have no torches display properly (icon crossed out).

Thanks.

**Comment by davelacorneille** [comment]
I confirm this behavior.

**Comment by leemahn** [comment]
> I confirm this behavior.

Thanks.  Any setting change that I can make to help solve it?

**Comment by davelacorneille** [comment]
I quick fix is to add at least 0 torch in the inventory.  If you have 0 torch (I mean having the torch item with the qty at 0) the button will be deactivate in the hub of that actor.

**Comment by leemahn** [comment]
Ah.. ok.  I'll try that.  Thanks.

**Comment by lupestro** [comment]
I think you will find it better behaved in v10 - except that a GM can always apply the "Self" light source to any player, whose brightness is set by a module setting, for those GMs who don't want to mess with items, etc. for lighting. v10 features a bunch of light sources and is extensible. (Don't move to V10 until your system and all your modules have updated. You can tell when V10 is ready for the way you use Foundry - your modules, etc. - by installing the Module Compatibility Checker module in V9.

**Comment by lupestro** [comment]
Having heard nothing more on this since August, I am closing this one. It sounds like this is resolved to everyone's satisfaction. If not, feel free to open a new ticket so we can see what to pursue.
