### ISSUE TITLE
Torch changes token settings

### ISSUE THREAD

**Issue by Jensenator360** [League-of-Foundry-Developers/torch#22]
When I disable and enable the characters light-source, it changes the light intensity and I need to manually change the settings back.
![chrome_Hjhl3wNSEL](https://user-images.githubusercontent.com/74561762/188393344-424b6909-f21a-40d0-9913-61d0fd3c5105.png)

**Comment by lupestro** [comment]
Based on your statement of the issue, I'm not sure what you expected, and I want to make sure that I respond to the right issue.

* Did you expect that the light source would become some other entity, connected to or placed with the token whose HUD you were using, but existing independently?
* Did you expect, when the light source was on, that you'd adjust the light level manually, and then that would be the light level used for that light source?

Here is how it works today:

* The token whose HUD you open *is* your light source. There is no other entity involved. 
* You can select different source types by right-clicking on the torch icon, bringing up a context menu of icons below the torch.
* When you toggle the icon "on", we adjust the token's light settings according to presets for the type of light source that you have selected. 
* When you toggle the icon "off", the token's light settings are reset to the values from the actor's prototype token, presumed to be the character's natural luminescence level (typically 0 for most creatures.)
* You can add new light source types or override the presets of an existing type by supplying a JSON file as described in the README. 
* The "dancing lights" light source (supported only for historic reasons) creates four new light sources near (perhaps too near) the actor's token which can be moved independently of the actor's token and one another. This is the only light source that does that.

I'm interested in how you were expecting it to work. I'm always open to new and perhaps better ways of doing things. Whatever you expected might offer the seeds of doing something a better way, providing opportunities for useful features.

Torch is, in many ways, very limited. It provides a simple and primitive interface for "flicking your Bic." I just added a way to select what kind of Bic to flick, but that's about it.

* For instance, Torch implements the "light" cantrip with unreasonable limitations. According to the SRD rules, light should be able to be cast on an object other than the caster and then move with that object. Torch  has no provision for that.
* Torch provides no way for a character to set up a lamp, place it on the other side of the room, and step away to hide. 
* Torch doesn't support the notion of both the character and the torch shedding light independently.

 In "high-automation" environments, I suspect that an artful combination of MATT and ATL would be the best answer for each of these, something more integrated in the normal play of games like D&D5e and Pathfinder, where the player invokes the item itself from the Token Action HUD or some such thing. However, if changes could be made so Torch could provide a baseline fallback for primitive "pick-up"/"set-down"/"attach" of light sources on systems that aren't supported by that level of automation - without sacrificing operating simplicity - that'd be great.

So let me know what you expected to happen, how you expected it would work, and we can explore it together a bit. Feel free to chat me up on Discord as well to bat this thing around.

**Comment by RedVanGhoul** [comment]
The README.MD doesn't say how to do this.  Is there a different readme I should be looking at?  

I am having a similar problem where activating a light will override the light angle setting on a character.  In Foundry v9, I could simply set "Light Angle" to 60 and activating Torch would respect that angle limit.  Now, it seems to be pulling information from a Flashlight item in my player's inventory (Savage Worlds) and automatically changes it to an angle of 3.

I have no idea where that information is saved for the flashlight itself and fiddling around with Torch's settings in the game do not seem to get the desired results.  And the readme that is available doesn't offer the proper syntax for a JSON to override this.

**Comment by lupestro** [comment]
Also, v10 was published from the v10 branch, not the main branch, which still has the old v9 code from before the rework, so the README.md that contains the instructions is on that branch.

**Comment by lupestro** [comment]
@Jensenator360 When you say "it changes the light intensity", is this a situation where you change a property on the light other than the radii? 

When we were only messing with the radii, we could leave the rest of it alone, but now that a light definition can affect just about any light property, the approach you are used to would get blown away by some of the light source definitions.

To make it possible to control things through settings alone, I am thinking of adjusting the behavior for the light source named in settings to combine the specified radii with the light properties from the actor's prototype token, so you'd apply your other settings to the prototype token, rather than the token on the scene. 

This should bring you back to somewhere near where you were.  Does this sound workable?

**Comment by lupestro** [comment]
@Jensenator360 In the next update, I am adjusting the handling of the bright/dim config settings to set all of the other light properties from the prototype token of the actor. This lets you set them up in advance in much the way you did before, only using the prototype token.

**Comment by lupestro** [comment]
I have made the indicated improvement in Torch v2.1.3. @Jensenator360 Let me know if it doesn't address the problem you saw.

**Comment by lupestro** [comment]
@Jensenator360 Having heard nothing for a couple of months now, I am going to behave as if everything is settled and close this ticket. In any case, with the updated software, the situation will have at least changed and responding to new circumstances will need a fresh ticket. Feel free to open it if the solution wasn't satisfactory.
