### ISSUE TITLE
 the translations are not working

### ISSUE THREAD

**Issue by eunaumtenhoid** [League-of-Foundry-Developers/torch#24]
the translations are not working, they are always in English

**Comment by lupestro** [comment]
Thanks for calling this to my attention - sorry for the delay in looking in on GitHub

**Comment by lupestro** [comment]
@eunaumtenhoid I just tried the Spanish translation and when I go into settings, I see that it is working on my system (with three untranslated strings, unfortunately. Which translation are you working with? Were the config settings coming through correctly?

The tooltips on the light sources are all in English, unfortunately, and it is recognizing the English names for the items only.  This is a known limitation at present, as we don't have translated sources.json files for each language. This is important to address but it will take a little time. I need to go through the translations of each of the compendia for each of the systems for each of the languages and pull the names out.

In the meantime, I'd like to be sure that you are at least getting the translations for the settings showing up.

**Comment by eunaumtenhoid** [comment]
hmmm, I understand, thanks for the clarification, in this case I'm using pt-BR

**Comment by lupestro** [comment]
Upon further investigation, it turns out that there was a flaw in the translation files for four of the languages.

**Comment by lupestro** [comment]
This has been verified failed in previous releases and verified fixed in Torch v2.1.3.
