### ISSUE TITLE
Issue extending light sources in Alien RPG from ICronyl

### ISSUE THREAD

**Issue by lupestro** [League-of-Foundry-Developers/torch#32]
Hello,

I am trying to use this module for Alien RPG, but to no avail. I'm sure there's something i'm missing, but i can't find what it is.
I'm using V9, and have made a file named "customsources.json" in the torch directory

Here's the content:
```
{
  "alienrpg": {
    "topology": "standard",
    "sources": {
      "Hi-beam Flashlight": {
        "consumable": false,
        "light": [
          { "bright": 10, "dim": 15, "angle": 90, "color": "#ff9329", "alpha": 0.5,
          "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
        ]
      },
      "TNR High Beam Shoulder Lamp": {
        "consumable": false,
        "light": [
          { "bright": 10, "dim": 15, "angle": 90, "color": "#ff9329", "alpha": 0.5,
          "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
        ]
      },
      "Land Vehicle Lights": {
        "consumable": false,
        "light": [
          { "bright": 15, "dim": 20, "angle": 90, "color": "#ff9329", "alpha": 0.5,
          "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
        ]
      }
    }
  }
}
```
Thanks in advance

_Originally posted by @ICronyI in https://github.com/League-of-Foundry-Developers/torch/issues/27#issuecomment-1336795970_

**Comment by lupestro** [comment]
More from ICronyl in #27:
> @Tarubain Hey! yeah it's always nice to meet Free league players, i also do play Tales from the loop myself and it's great :) Thank you for this, i checked with visual code and corrected the code, it is now like this:
> 
> ```
> 
> {
>   "alienrpg": {
>     "topology": "standard",
>     "sources": {
>       "Hi-beam Flashlight": {
>         "consumable": false,
>         "light": [
>           { "bright": 10, "dim": 15, "angle": 90, "color": "#ff9329", "alpha": 0.5,
>           "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
>       }]
>       },
>       "TNR High Beam Shoulder Lamp": {
>         "consumable": false,
>         "light": [
>           { "bright": 10, "dim": 15, "angle": 90, "color": "#ff9329", "alpha": 0.5,
>           "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
>       }]
>       },
>       "Land Vehicle Lights": {
>         "consumable": false,
>         "light": [
>           { "bright": 15, "dim": 20, "angle": 90, "color": "#ff9329", "alpha": 0.5,
>           "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
>       }]
>       }
>     }
>   }
> }
> ```
> 
> It doesn't show any errors anymore in visual code, however it still doesn't work sadly :/

**Comment by lupestro** [comment]
@ICronyI Try the above with v2.2.0 of Torch. You can even eliminate the "topology" and "consumable" properties because the values you are supplying are the defaults. Let me know how it goes. In the meantime, I'll load up Alien RPG tonight and take a look.

**Comment by ICronyI** [comment]
@lupestro 
As i mentioned in my first post, i'm using V9 of Foundry VTT, which i think will prevent me from trying out v2.2.0 of Torch currently if i'm not mistaken?

**Comment by lupestro** [comment]
Oh, darn. Yeah, sorry!

**Comment by ICronyI** [comment]
I tried updating the code, it now looks like this:
```
{
  "alienrpg": {
    "topology": "standard",
    "quantity" : "attributes.quantity",
    "sources": {
      "Hi-beam Flashlight": {
        "name": "Hi-beam Flashlight",
        "type": "equipment",
        "consumable": false,
        "states": 2,
        "light": [
          { "bright": 10, "dim": 15, "angle": 90, "color": "#ff9329", "alpha": 0.5,
          "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
      }]
      },
      "TNR High Beam Shoulder Lamp": {
        "name": "TNR High Beam Shoulder Lamp",
        "type": "equipment",
        "consumable": false,
        "states": 2,
        "light": [
          { "bright": 10, "dim": 15, "angle": 90, "color": "#ff9329", "alpha": 0.5,
          "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
      }]
      },
      "Land Vehicle Lights": {
        "name": "Land Vehicle Lights",
        "type": "equipment",
        "consumable": false,
        "states": 2,
        "light": [
          { "bright": 15, "dim": 20, "angle": 90, "color": "#ff9329", "alpha": 0.5,
          "animation": { "type": "torch", "speed": 2, "intensity": 5, "reverse": false }
      }]
      }
    }
  }
}
```
But it still doesn't work unfortunately :(

**Comment by lupestro** [comment]
@ICronyI Did you ever get out of v9-land? Is this something to revisit?

**Comment by ICronyI** [comment]
@lupestro Sorry i just noticed your message! 
I have since then updated to V10, and no issue to report :)
Thank you for your help!
