### ISSUE TITLE
Manifest URL needs updating

### ISSUE THREAD

**Issue by ckdragons** [League-of-Foundry-Developers/torch#33]
![image](https://user-images.githubusercontent.com/84493092/206094119-961c9cc9-fedd-45d7-ac3f-b6c10279db02.png)

Manifest URL for 2.2.0 points to 2.1.4

**Comment by lupestro** [comment]
Whoops! Fixed the branching but missed it in the manifest. Thanks for the heads up!

**Comment by lupestro** [comment]
Should be fixed in release 2.2.1 
@ckdragons Please verify its all okay now?
