### ISSUE TITLE
Call the One-Button via Macro

### ISSUE THREAD

**Issue by Tarubain** [League-of-Foundry-Developers/torch#35]
Hi @lupestro !

We love your module and it is working great now with your help. 😊

However, my players are asking if it is possible to toggle the One Button or even specific light sources with a Macro? Is there maybe a documentation I missed?

**Comment by lupestro** [comment]
Nope - I didn't include an API for macro use. Probably won't have it for you this week, but I'll put it on the radar, for sure. Good idea.

**Comment by lupestro** [comment]
Heads up - they're coded :) I just need to get a release out. I finally got the energy to give this module a little love. This release delivers on a number of things we've talked about in the issues over the past two years.

**Comment by lupestro** [comment]
This is now delivered in 2.8.0. The README.md has the list of methods available to macro writers. It should be reasonably comprehensive.
