### ISSUE TITLE
DCC

### ISSUE THREAD

**Issue by marcusadmortati** [League-of-Foundry-Developers/torch#37]
The mod is excellent! Would it be possible to include DCC (Dungeon Crawl Classics) in the list of systems configured?

**Comment by lupestro** [comment]
@marcusadmortati Ah, so the system comes with a compendium of items and the light sources are in it. That sounds like it's an excellent candidate to include. You want to create a custom JSON you can put into your game through the config to try it out, kick the tires, and then pass it back to me to get into the set delivered with the module? (I'll credit you with the contribution in the changelog, of course.)

**Comment by marcusadmortati** [comment]
Right! I'll try here, coding is far from my skill.

**Comment by marcusadmortati** [comment]
I believe what you are asking for is this. I apologize in advance for any errors, I have no coding skills.

{
  "dcc": {
    "system": "dcc",
    "topology": "standard",
    "quantity" : "quantity",
    "aliases": {
      "Torch, each": "Torch, each",

    }
    "sources": {
      "Torch, each": {
        "name": "Torch, each",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          { 
            "bright": 15, "dim": 30, "angle": 360, "color": "#ff9329", "alpha": 0.5,
            "animation": { "type": "torch", "speed": 5, "intensity": 2, "reverse": false } 
          }
        ]
      }
    }
  },
  ...
}

**Comment by lupestro** [comment]
When I bring up a fresh DCC world, I see two compendia: User Guide and DCC Macros. Where are your items coming from?

**Comment by marcusadmortati** [comment]
No, it comes from the DCC Core Book Compendium.
![image](https://user-images.githubusercontent.com/74226256/206871559-4d3e5fe6-9c8f-47f3-8c3d-1ffe18c27a5f.png)

**Comment by lupestro** [comment]
Ah, okay, I see, it's a Goodman Games premium module. Got it. So that's a bullet-two item and still a good candidate. 
Unfortunately hard for me to test here without shelling out for the module. :( 

What other light sources are there in those items? I see a Lantern. Are there candles as well? Do the rules give the bright/dim distances for each? Any cones, etc.? Can you post JSON with the whole list and verify everything goes on and off using it as an "Additional Light Sources" file? (By the way, you won't need an alias for anything you're doing so far, so you can omit that section.)

**Comment by marcusadmortati** [comment]
Only torch and lantern.
They are only listed as equipment, they do not have light parameters.

**Comment by lupestro** [comment]
You should be able to get the specs for the two light sources from the rule book in that module. Wrap 'em both up and we can go with them.

> Access all of the spells, equipment, critical hit and fumble tables, class descriptions, and **rules text** from the Dungeon Crawl Classics Core Rulebook from within Foundry! 

(from their blurb on DriveThruRPG, emphasis mine.)

**Comment by marcusadmortati** [comment]
My mistake, just a torch and a lantern.

**Comment by lupestro** [comment]
I would presume the flashlight is just MCC, right? And Goodman offers no licensed VTT material for MCC, so MCC stuff is going to be strictly a  GM-supplied JSON.

**Comment by marcusadmortati** [comment]
That is the question, in the licro itself there are no such parameters. What I'm going to pass on here are the values that the community uses.

Lantern: 15' bright, 30 dim;
Torch, each: 15' bright, 30 dim.

There is no official support for MCC yet.

**Comment by marcusadmortati** [comment]
Just as the parameters of the torches and lanterns are supported by the common sense of the DM's, we can arbitrate the MCC lantern...

**Comment by marcusadmortati** [comment]
The advantage of the lantern is the time it stays on.

**Comment by lupestro** [comment]
Okay, so both are comparable in illumination to a PF1 lamp. I presume Lantern should be consumable: false, another advantage. Make the JSON for those, test it, and I'll incorporate it.

**Comment by marcusadmortati** [comment]
I will try to do it.

**Comment by marcusadmortati** [comment]
Done. You will probably find errors...

{
  "dcc": {
    "system": "dcc",
    "topology": "standard",
    "quantity" : "quantity",
    "aliases": {
      "Torch, each": "Torch, each",
	  "Oil": "Oil"

    }
    "sources": {
      "Torch, each": {
        "name": "Torch, each",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          { 
            "bright": 15, "dim": 30, "angle": 360, "color": "#ff9329", "alpha": 0.5,
            "animation": { "type": "torch", "speed": 5, "intensity": 2, "reverse": false } 
		"Oil": {
        "name": "Oil",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          { 
            "bright": 10, "dim": 15, "angle": 360, "color": "#ff9329", "alpha": 0.5,
            "animation": { "type": "torch", "speed": 5, "intensity": 2, "reverse": false } 	
			
          }
        ]
      }
    }
  },
  ...
}

**Comment by marcusadmortati** [comment]
Worked!

Correction: the name of oil is Oil, 1 flask***

**Comment by lupestro** [comment]
I think I am going to do the Lantern with consumable: false rather than the "Oil, 1 flask". It's consistent with the approach taken on other systems. Try this, and if it works, we have something I can publish:
```json
{
  "dcc": {
    "system": "dcc",
    "topology": "standard",
    "quantity" : "quantity",
    "aliases": {
      "Lantern": "Oil"
    },
    "sources": {
      "Torch, each": {
        "name": "Torch, each",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          { 
            "bright": 15, "dim": 30, "angle": 360, "color": "#ff9329", "alpha": 0.5,
            "animation": { "type": "torch", "speed": 5, "intensity": 2, "reverse": false } 
          }
        ]
      },
      "Lantern": {
        "name": "Lantern",
        "type": "equipment",
        "consumable": false,
        "states": 2,
        "light": [
          { 
            "bright": 15, "dim": 30, "angle": 360, "color": "#ff9329", "alpha": 0.5,
            "animation": { "type": "torch", "speed": 5, "intensity": 2, "reverse": false } 	            
          }
        ]
      }
    }
  },
}
```
Sound like a plan?

**Comment by marcusadmortati** [comment]
It didn't work, the previous one did.

**Comment by lupestro** [comment]
Do you have the lantern itself in your equipment, or just the oil?

**Comment by marcusadmortati** [comment]
Oil>Oil, 1 flask***
Lantern> Lantern

**Comment by marcusadmortati** [comment]
How can I choose which light source to turn on?

**Comment by marcusadmortati** [comment]
I made some adjustments to alpha and intensity in the previous version, it's working. Only instead of the "Torch" animation, it lights up with the "Flickering Light".

**Comment by marcusadmortati** [comment]
The one that works is this one, with the adjustments I made, in intensity and alpha.

{
  "dcc": {
    "system": "dcc",
    "topology": "standard",
    "quantity" : "quantity",
    "sources": {
      "Torch, each": {
        "name": "Torch, each",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          { 
            "bright": 15, "dim": 30, "angle": 360, "color": "#ff9329", "alpha": 0.2,
            "animation": { "type": "torch", "speed": 5, "intensity": 5, "reverse": false } 
          }
        ]
      },
      "Oil": {
        "name": "Oil",
        "type": "equipment",
        "consumable": true,
        "states": 2,
        "light": [
          { 
            "bright": 15, "dim": 30, "angle": 360, "color": "#ff9329", "alpha": 0.2,
            "animation": { "type": "torch", "speed": 5, "intensity": 5, "reverse": false } 	            
          }
        ]
      }
    }
  }
}

**Comment by lupestro** [comment]
To switch light sources, right click on the one button and it gives you a context menu.

**Comment by marcusadmortati** [comment]
Great! Working here! Excellent job!
The interesting thing is that you managed to make a mod change the item's quantities, something that no mod could do in DCC, which is very interesting for any other mod to change the amount of consumables such as arrows and rations.

**Comment by lupestro** [comment]
Happily, DCC handles quantity in exactly the same way as many other systems, so it's just updating the embeddedItem.system.quantity. I'll get a release out. Thanks!

**Comment by marcusadmortati** [comment]
It wouldn't be possible without you!
Thanks! :)
