### ISSUE TITLE
Vision

### ISSUE THREAD

**Issue by brunocalado** [League-of-Foundry-Developers/torch#43]
Hi.

Can you make this also be able to change vision?

tks

**Comment by lupestro** [comment]
Give me more here to understand what you want to be able to do. In what sort of situation would a physical light source potentially affect the character's vision?

**Comment by brunocalado** [comment]
> Give me more here to understand what you want to be able to do. In what sort of situation would a physical light source potentially affect the character's vision?

I don't want it to work with light. It's to use with a spell. You cast Dark Vision and you change your vision settings. This would work without mess with light.

**Comment by lupestro** [comment]
I’m afraid that’s kind of “out of scope” for what this module does. There are other modules out there that can tie various effects to spells and they often have prefabs to do that. Some are specific to certain systems, but some get pretty broad. You can use something like Monk’s Active Tile Triggers to hook it to a tile or you can tie a macro to a UI button or to a condition. Ask over in module-discussion or macro-polo and someone can help you out.
