### ISSUE TITLE
Torch Button missing on all Tokens

### ISSUE THREAD

**Issue by NachoTeller** [League-of-Foundry-Developers/torch#48]
I have been playing with the Torch module since it was launched in my campaign with the OSE system. In one of the last updates something has happened that the torch button no longer appears on the tokens. I have tried with PCs and NPCs with and without torches in their inventory and it never comes up anymore. I play a lot of dungeons with Human characters who can't see in the dark and are constantly turning torches on and off, and right now the module has become totally useless for me.

I use Foundry v10 and the latest version of the Torch module.

**Comment by lupestro** [comment]
Help may be coming on this one - I've just been informed that the names "Torch" and "Lantern" didn't match the names in the premium OSE module. I'm getting the right names from someone who has the module and will correct the data and deliver a fix as soon as I get it.

**Comment by lupestro** [comment]
The real names have shipped in 2.8.0 - Are you on v10 or v11 yet? How is it going for you? Better ride with the new code?

Are you still having the original reported problem? If not, we can close this issue.

**Comment by lupestro** [comment]
@NachoTeller Just checking back on this one - if I don't hear from you in a week or two, I'll assume you've moved on and close the issue.
