### ISSUE TITLE
Code for advanced light options?

### ISSUE THREAD

**Issue by peterprokurist** [League-of-Foundry-Developers/torch#55]
What is the code to set the new AdvancedOptions? Like "Luminosity" or "Contrast"? I've tried a lot, but I can't get any further.
Thx.
![image](https://github.com/League-of-Foundry-Developers/torch/assets/115837717/94c0cf37-cd3e-41e9-8f1e-cfea4544482a)

**Comment by lupestro** [comment]
Any names in here should work:
<img width="641" alt="image" src="https://github.com/League-of-Foundry-Developers/torch/assets/1447893/0cebdadd-3b14-4023-91bc-8c55e8d491d9">

**Comment by lupestro** [comment]
Let me know if that got you what you needed. If so, I'll close this issue. If you need more, I'll keep an ear open. :)

**Comment by peterprokurist** [comment]
thanks for the reply!
the code works almost perfectly.
only one important setting does not work: the animation type.
I've tried everything possible, but no matter what I set, the animation doesn't change :-(

![licht](https://github.com/League-of-Foundry-Developers/torch/assets/115837717/10bc015c-4650-4dd2-9b46-47d0de19cfd5)

**Comment by peterprokurist** [comment]
Ah, I got it.
The value for "type" is not a number but the name of the animation (as it says in the "Customizing light sources" section).
BUT: as soon as you want to choose compound names, you have to try. The "Energy Field" is called "energy", the "Bewitching Wave" is called "wave".
Now everything works.
Thank you all !!!

![licht](https://github.com/League-of-Foundry-Developers/torch/assets/115837717/6d7fa10a-2785-49f0-b92f-818f240e1d32)
