### ISSUE TITLE
[SWADE] Dim radius is not set correctly

### ISSUE THREAD

**Issue by ddbrown30** [League-of-Foundry-Developers/torch#71]
Not sure if this is only a SWADE problem, but when clicking the torch button, it sets the light radius to Dim 4 and Bright 4. With the way lights work, this is basically the same as Dim 0 Bright 4. The correct values should be Dim 8 Bright 4.

**Comment by lupestro** [comment]
You seem to have figured out what is going on. I’ll take the confusion you experienced as input for upcoming changes, tracking it with your more recent ticket and I’ll close this one.
