### ISSUE TITLE
Supply Exhausted even though I have >1 torch in inventory

### ISSUE THREAD

**Issue by brennanmuir** [League-of-Foundry-Developers/torch#80]
Testing with two different torches I had imported from separate compendiums, but I am receiving a "Supply Exhausted" error when I try to activate a player's torch. 

I have deactivated and reactivated the module and refreshed my foundry instance both with/without cache.

![image](https://github.com/League-of-Foundry-Developers/torch/assets/18177606/54995aff-c937-4b83-8030-101eb686e460)

**Comment by lupestro** [comment]
You have two things called Torch, which might conceivably confuse things. Even so, the worst that can happen is you get the wrong one, and both have inventory. 

I haven't seen anything like this before. This is clearly D&D5e - Can you send me an export of your character? Also, what version of Foundry, the system, the module, etc. so I can reproduce the situation. I'd like to look into it.

**Comment by brennanmuir** [comment]
My apologies for the late reply. I think the duplicates were one item imported from 5e.tools via Plutonium and the other was SRD or DND Beyond. 

Foundry v11.315
System 5e 3.2
Module 2.13.1

Please let me know if there's anything else you need. Again, sorry for the delay

**Comment by brennanmuir** [comment]
After taking a quick look at the JSON, it looks like there are two torch items. One with an inventory of zero. I removed that and it resolved the issue. Sorry for the trouble but thank you for responding and ultimately guiding me to the solution.
