### ISSUE TITLE
Suggestion for Helpful Error Message in Torch Module

### ISSUE THREAD

**Issue by dugedog** [League-of-Foundry-Developers/torch#87]
I’m fairly new to this, but I wanted to share something I encountered using the Torch module. I got the error "**_Loading User Sources Failed, JSON5: invalid character '<' at 1:1_**" whenever I right click on an Actor. After some digging, I realised it was because the JSON file for "Additional Light Sources" was missing (I'm not sure when it disappeared to). Maybe a message to the effect of "**_Error: Missing JSON File for Additional Light Sources. Please check the file path in Settings and ensure the file exists._**" would make it clearer. 

Just a suggestion! Thanks for all the work on the module—I really appreciate it!

**Comment by lupestro** [comment]
I’m sure I had a test for a missing file in my suite. It should have picked up the 404 code from the fetch. I’ll double down on that. 

You’re right - the message you get when it tries to read the error HTML contents as JSON is terribly confusing. All apologies.

**Comment by lupestro** [comment]
Fixed in 2.15.1, just published.

**Comment by dugedog** [comment]
Hi Ralph.

That new message looks clear. Thanks for updating that!
