### ISSUE TITLE
Torch seems to be looping through the JSON load after the latest update.

### ISSUE THREAD

**Issue by Stonedtroll** [League-of-Foundry-Developers/torch#91]
Torch seems to be looping through the JSON load after the latest update.

![image](https://github.com/user-attachments/assets/027343fa-8d34-41d5-9c9a-23b41636562b)

Foundry v12.331
D&D5e .3.3.1
Torch v2.15.1

**Comment by Stonedtroll** [comment]
Uninstall/install seems to fix the issue.

**Comment by Stonedtroll** [comment]
It came back...

**Comment by lupestro** [comment]
I’ll see what I can figure out, but it may be the weekend before I get there. RL work is going to be busy the latter part of this week.

**Comment by Stonedtroll** [comment]
Absolutely no urgency at all. Already grateful that this mod exist.

**Comment by lupestro** [comment]
Any chance you can post your custom light source file here? It may help me to see what could be failing...

**Comment by Stonedtroll** [comment]
Here it is:

[Torch Source Dark.json](https://github.com/user-attachments/files/17331430/Torch.Source.Dark.json)

**Comment by lupestro** [comment]
It will load the document fairly frequently, at the least, every time you open the token HUD - in case you tweaked the JSON file in place in your world. That's normal. It's a fast load so it doesn't cost much to do it frequently. However, I'm having some difficulty reproducing the error you are seeing. 

I can see that it is failing in "Hud.addTorchButton" and that the object it is dereferencing "document" from is undefined. The only  object with a .document in that code is "hud.object". That function is fired by the "renderTokenHud" hook and hud is the token hud's app, the first parameter. As far as I know, the hud.object should always exist, as it is just a part of how the hud works. In any case, it is created in core code, so shouldn't vary from one install of Foundry 12.331 to the next (or even from one system to the next, unless the system is doing something funky.)

I am not working with a 3.3.1 install of DnD5e here and nobody else has reported this peculiar problem. Do you have any modules enabled? (I suspect just about *everyone* running DnD5e has at least a few.) Could one of those modules be clobbering the properties of the token hud app? 

In the meantime, I will double check whether the members of the Token HUD app have changed. If the Token HUD became an Appv2 application, something could have shifted out from under me, and maybe there's a better supported way to find the token's actor than `app.object.document.actorId`.

If we can get into chat on Discord at some point when this is happening, I would like to see exactly what properties the token hud app has at point of entry. 

Thank you for your forbearance.

**Comment by Stonedtroll** [comment]
Let me see if the error is still happening. If it is, I'll create a testbed with just this module.

**Comment by Stonedtroll** [comment]
Can no longer reproduce so I think you're right. I should have checked that first. The error message gave me false confidence that the culprit was Torch. Apologies and thanks again for taking the time.
