### ISSUE TITLE
Feature request (maybe) add "walls" parameter

### ISSUE THREAD

**Issue by misthero** [League-of-Foundry-Developers/torch#93]
not sure if I'm doing it wrong or is a bug or is not implemented, I'd like to make a light that see behind walls, this is possible in foundry with the parameter "walls": false

![image](https://github.com/user-attachments/assets/e0f7fcfe-8d62-4f92-9b3c-9fde37674d85)

anyway I tried in the custom light json and it gets ignored.

![image](https://github.com/user-attachments/assets/a554a850-5d11-4a7b-adbb-7dbc490d1edd)

Am I doing it wrong?

**Comment by lupestro** [comment]
The problem here is that this isn't really an external "light source" that moves with the actor, but a temporary setting of the light parameters on the token itself, so if you can't set it in the token Light settings, it isn't available.

**Comment by misthero** [comment]
oh I see, that clarify how the module works, I assumed it was the same of any light source. Than you can close this issue.

thanks for your work!
